services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000"
    environment:
      - PORT=3000
      - DB_CONNECTION=postgres
  database:
    image: postgres:14-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./asd:/asd
      - /asdf:/asdf
      - type: bind
        source: ./app
        target: /app
        read_only: true
    environment:
      - POSTGRES_DB=database
      - POSTGRES_PASSWORD=password
